@startuml
'https://plantuml.com/component-diagram

package "Online" {
    [API платежей]
    [Сервис Лимитов]
}

package "Offline" {
  [Проведение платежей]
  [Интеграция с платежными системами]
}

package "Сервис нотификаций" {
    [Отправка уведомлений пользователей о платежах]

}

cloud "Платежный системы" {
    [Платежные системы]
}

database OLTP {
    [Лимиты]
    [Платежи не в финальном статусе]
    [Очереди и блокировки платежей ]
}

database Warehouse {
    [Исторические данные о платежах]
}

package "Backoffice" {
    [Учет и синхронизация реестров между платежными системами]
}

[Интеграция с платежными системами] -> [Платежные системы]

Offline -> [Платежи не в финальном статусе]
Online -> OLTP



@enduml